### ISSUE TITLE
Fix NGINX proxy for the sensu healthcheck

### ISSUE THREAD

**Issue by dtest** [pythian/opsviz#46]
Uchiwa makes an API call to this address:

(dashboard_url)/sensu/health/sensu

This is supposed to return an object similar to this:

```json
{"Sensu":{"output":"ok"}}
```

However, nginx is redirecting it to the events page. This causes the alerts on datacenter being undefined due to the way javascript is parsing it.

![screen shot 2015-03-17 at 5 24 39 pm](https://cloud.githubusercontent.com/assets/700224/6697928/88b1cb40-ccca-11e4-8e64-f39cd083b1ac.png)

**Comment by dtest** [comment]
This is the issue: 
https://github.com/pythian/opsviz/blob/master/site-cookbooks/bb_monitor/templates/default/nginx/dashboard.erb#L30

I just don't know the reasoning behind this rule. Can we rewrite Line 31 to be a permanent?

**Comment by jmetzmeier** [comment]
Nice job tracking this down. :+1:
