### ISSUE TITLE
Nginx is appending a slash to many paths

### ISSUE THREAD

**Issue by jonathandietz** [pythian/opsviz#53]
Nginx is appending a slash to the end some of the urls and it shouldn't be. I think this is causing some issues with some things.

`/elasticsearch/_nodes` is actually this when it hits the ES server: `[elasticsearch]:9200//_nodes` (notice the double slash).

Marvel needs to be accessed like this: `[doorman_elb]/elasticsearch_plugin/marvel` and may redirect you the first run.

I can see there is a trailing slash here: `https://github.com/pythian/opsviz/blob/master/site-cookbooks/bb_monitor/templates/default/nginx/dashboard.erb#L22`. Removing that trailing slash should be the proper way to set this up. I also notice that many of the other routes are doing the same thing. If there isn't a specific reason those are setup like that I'll go ahead and fix this.

**Comment by alexlovelltroy** [comment]
I think fixing elasticsearch and sensu at the very least would be helpful
