### ISSUE TITLE
Add RabbitMQ management plugin to dashboard

### ISSUE THREAD

**Issue by jonathandietz** [pythian/opsviz#54]
RabbitMQ has a dashboard https://www.rabbitmq.com/management.html

It runs on the RabbitMQ server over port 15672. The RabbitMQ ELB has a listener for port 15672, but the external security group for that ELB only uses port 5671. https://github.com/pythian/opsviz/blob/master/cloudformation.json#L1182

We should make sure this dashboard plugin is installed and available on the dashboard. It probably makes sense to use the Dashboard ELB and Nginx to forward /rabbitmq to the RabbitMQ ELB on port 15672. This puts the RMQ dashboard behind Doorman's authentication.

**Comment by alexlovelltroy** [comment]
fixed in the alovelltroy-bugfix branch
